// lyka-react/src/components/ImageSelector.js
import React from 'react'
import styled from 'styled-components'

import Image1 from '../assets/images/green-apple2.png'
import Image2 from '../assets/images/half-apple.png'
import Image3 from '../assets/images/green-apple-flipped.png'
import Image4 from '../assets/images/apple-top.png'

const Container = styled.div`
    background: var(--white);
    padding: 20px;
    border-bottom-left-radius: var(--border-radius);
    border-bottom-right-radius: var(--border-radius);
`

const List = styled.ul`
    display: flex;
    justify-content: space-between;
    list-style: none;
    margin: 0;
    padding: 0;
`

const Item = styled.li`
    border: 1px solid var(--grey);
    border-radius: calc(var(--border-radius) / 2);

    :hover {
        cursor: pointer;
    }
`

const ImageSelector = () => {
    return (
        <Container>
            <List>
                <Item className="imageSelector-list-item"><img src={Image1} alt={Image1} /></Item>
                <Item className="imageSelector-list-item"><img src={Image2} alt={Image2} /></Item>
                <Item className="imageSelector-list-item"><img src={Image3} alt={Image3} /></Item>
                <Item className="imageSelector-list-item"><img src={Image4} alt={Image4} /></Item>
            </List>
        </Container>
    )
}

export default ImageSelector

// lyka-vue/src/components/ImageSelector.vue
<template>
  <div class="imageSelector">
        <ul class="imageSelector-list">
            <li class="imageSelector-list-item"><img src='@/assets/images/green-apple2.png' alt="green apple" /></li>
            <li class="imageSelector-list-item"><img src='@/assets/images/half-apple.png' alt="half apple" /></li>
            <li class="imageSelector-list-item"><img src='@/assets/images/green-apple-flipped.png' alt="flipped apple" /></li>
            <li class="imageSelector-list-item"><img src='@/assets/images/apple-top.png' alt="apple top" /></li>
        </ul>
    </div>
</template>

<script>
export default {
    name: 'ImageSelector'
}
</script>

<style>

.imageSelector {
  background: #fff;
  padding: 20px;
  border-bottom-left-radius: var(--border-radius);
  border-bottom-right-radius: var(--border-radius);
  
}

.imageSelector-list {
  display: flex;
  justify-content: space-between;
  list-style: none;
  margin: 0;
  padding: 0;
}

.imageSelector-list-item {
  border: 1px solid var(--grey);
  border-radius: calc(var(--border-radius) / 2);
}

.imageSelector-list-item:hover {
  cursor: pointer;
}

</style>
