// lyka-vue/src/components/ProductCard.vue
<template>
  <div class="productCard">
    <HeroCard />
    <div class="cardContent">
      <h2 class="productName">Delicious Apples</h2>
      <div class="productCode">COD: 45999</div>
      <div class="price">
        R$
        <span class="price-value">7.93</span>
      </div>
      <!-- Should have a quantity selector here -->
      <ColorSelector />
      <Benefits />
      <Button />
    </div>
  </div>
</template>

<script>
import HeroCard from './HeroCard'
import ColorSelector from './ColorSelector'
import Benefits from './Benefits'
import Button from './Button'

export default {
	name: 'ProductCard',
	components: {
		HeroCard,
		ColorSelector,
    Benefits,
    Button
	}
};
</script>

<style>
.productCard {
  background: #fff;
  border-radius: var(--border-radius);
  padding: 2rem;
  display: grid;
  grid-template-columns: 50% 50%;
  align-items: center;
}

.productName {
  margin: 0;
  font-weight: bold;
}

.productCode {
  color: var(--grey);
}

.price {
  color: var(--red);
  margin-top: 1.5rem;
  margin-bottom: 1rem;
}

.price-value {
  font-size: 4rem;
  margin-left: 1rem;
}
</style>

// lyka-react/src/components/ProductCard.js
import React from 'react'
import styled from 'styled-components'

// COMPONENTS
import Benefits from './Benefits'
import HeroCard from './HeroCard'
import ColorSelector from './ColorSelector'
import Button from './Button'
// import Selector from './Selector'

// STYLES
const Container = styled.div`
    background: var(--white);
    border-radius: var(--border-radius);
    padding: 2rem;
    display: grid;
    grid-template-columns: 50% 50%;
    align-items: center;
`

const ProductName = styled.h2`
    margin: 0;
    font-weight: bold;
    color: var(--dark);
`

const ProductCode = styled.div`
    color: var(--grey);
`

const Price = styled.div`
    font-size: 1.2rem;
    color: var(--red);
    margin-top: 1.5rem;
    margin-bottom: 1rem;
`

const Value = styled.span`
    font-size: 4rem;
    margin-left: 1rem;
`

// TEMPLATE
const ProductCard = () => {
    return (
        <Container>
            <HeroCard />
            <div>
                <ProductName>Delicious Apples</ProductName>
                <ProductCode>COD: 45999</ProductCode>
                <Price>R$ <Value>7.93</Value></Price>
                <ColorSelector />
                {/* <Selector /> */}
                <Benefits />
                <Button primary label='add to cart' />
            </div>
        </Container>
    )
}

export default ProductCard
